# Generated by Django 2.2.6 on 2019-11-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191024_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('not-specified', 'Not Specified'), ('female', 'Female')], max_length=80, null=True),
        ),
    ]
